# Generated by Django 4.0.6 on 2022-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDoctorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
