# Generated by Django 4.0.6 on 2022-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0002_rename_description_diseasedoctorrelation_disease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='doctor',
            field=models.TextField(max_length=200),
        ),
    ]
