# Generated by Django 4.0.6 on 2022-07-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0003_alter_diseasedoctorrelation_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='doctor',
            field=models.CharField(max_length=200),
        ),
    ]
