# Generated by Django 4.0.6 on 2022-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0004_alter_diseasedoctorrelation_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
