# Generated by Django 4.0.6 on 2022-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0005_alter_diseasedoctorrelation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
