# Generated by Django 4.0.6 on 2022-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0006_alter_diseasedoctorrelation_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease',
            field=models.CharField(max_length=100, verbose_name='disease'),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease_description',
            field=models.TextField(max_length=2000, verbose_name='disease_description'),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='doctor',
            field=models.CharField(max_length=100, verbose_name='doctor'),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
