# Generated by Django 4.0.6 on 2022-07-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0008_remove_diseasedoctorrelation_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedoctorrelation',
            name='disease',
            field=models.CharField(default='no', max_length=100, verbose_name='disease'),
        ),
        migrations.AddField(
            model_name='diseasedoctorrelation',
            name='disease_description',
            field=models.TextField(default='no', max_length=2000, verbose_name='disease_description'),
        ),
        migrations.AddField(
            model_name='diseasedoctorrelation',
            name='doctor',
            field=models.CharField(default='no', max_length=100, verbose_name='doctor'),
        ),
    ]
