# Generated by Django 4.0.6 on 2022-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0009_diseasedoctorrelation_disease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsforMultiselector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='disease_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='diseasedoctorrelation',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
